### ISSUE TITLE
Link to ecommerc blank templates - Let it work

### ISSUE THREAD

**Issue by Dirklensley** [louisevanderlith/mango#14]
https://startbootstrap.com/template-categories/ecommerce/

Also check if Payfast will work?

https://www.payfast.co.za/accept-payments-easy-way/?utm_source=google&utm_medium=cpc&utm_campaign=payfast_signup&gclid=CjwKEAjw6szOBRCF2sPTjfrJuXASJADDOLEFi1mv7Kvo2zVs7V1l5j5wT0tO14M1fNdguaNGJQ03wBoCpzjw_wcB

**Comment by Dirklensley** [comment]
Template - 

https://www.bootply.com/FRD7whzbaP

**Comment by louisevanderlith** [comment]
Sal hom in gooi.
